import Head from "next/head"
import styles from "../styles/Home.module.css"
import { useTheme, Switch, Text } from "@nextui-org/react"
import useDarkMode from "use-dark-mode"
import { HeroLatestPosts } from "../components"

export default function Home() {
  const { theme } = useTheme()
  const { isDark, type } = useTheme()
  const darkMode = useDarkMode(false)

  const posts = [
    {
      title: "lorem ipsum dolor sit amet consectetur adipisicing elit",
      image: "https://picsum.photos/id/1/400/400",
    },
    {
      title: "Post 2",
      image: "https://picsum.photos/id/2/400/400",
    },
    {
      title: "Post 3",
      image: "https://picsum.photos/id/3/400/400",
    },
    {
      title: "Post 4",
      image: "https://picsum.photos/id/4/400/400",
    },
    {
      title: "Post 5",
      image: "https://picsum.photos/id/5/400/400",
    },
    {
      title: "Post 6",
      image: "https://picsum.photos/id/6/400/400",
    },
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>Codemy Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <HeroLatestPosts posts={posts} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  )
}
